#!/bin/zsh
#./Functions/format_time.sh

format_time() {
    local remanderMinutes=$(($1 % 3600))
    local remander_seconds=$(($remanderMinutes % 60))

    local Formated_hours=$(printf '%02d' $(($1 / 3600)))
    local formated_minutes=$(printf '%02d' $(($remanderMinutes / 60)))
    local formated_seconds=$(printf '%02d' $(($remander_seconds % 60)))

    echo $Formated_hours:$formated_minutes:$formated_seconds
}

nasCatalogPath="/Volumes/NAS-Lightroom/LightroomCatalogs/"
sourceCatalogPath="/Users/xenomorph/Pictures/LightroomCatalogs/"
# echo "Do you want to back up NAS (y/N)"
# read includeNas 
# mount_smbfs $sourcePath/Developer /Volumes/TimeMachineExternal/xenomorph/Developer

echo "---------------------------------------------"
echo "---------------------------------------------"
echo "Mounting drive and starting Sync"
echo "---------------------------------------------"
echo "---------------------------------------------"
SECONDS=0
# diskutil mount LightroomBak

echo "---------------------------------------------"
echo "Syncing Lightroom Catalog Backup"
echo "---------------------------------------------"

rsync -av --delete $sourceCatalogPath $nasCatalogPath

echo "---------------------------------------------"
echo "Syncing Lightroom Catalog Backup"
echo "---------------------------------------------"


echo "---------------------------------------------"
echo "Completed runtime: $(format_time $SECONDS)"
echo "Source image count: \t\t$(ls -1R ~/Pictures|wc -l)"
echo "Destination image count: \t$(ls -1R /Volumes/LightroomBak/Pictures|wc -l)"
echo "Source video count: \t \t$(ls -1R ~/Movies|wc -l)"
echo "Destination video count: \t$(ls -1R /Volumes/LightroomBak/Movies|wc -l)"
echo "---------------------------------------------"

diskutil eject LightroomBak