#!/bin/zsh
#./Functions/format_time.sh

format_time() {
    local remanderMinutes=$(($1 % 3600))
    local remander_seconds=$(($remanderMinutes % 60))

    local Formated_hours=$(printf '%02d' $(($1 / 3600)))
    local formated_minutes=$(printf '%02d' $(($remanderMinutes / 60)))
    local formated_seconds=$(printf '%02d' $(($remander_seconds % 60)))

    echo $Formated_hours:$formated_minutes:$formated_seconds
}

nasDestinationPath="/Volumes/NAS-Lightroom/Lightroom"
sourcePicturesPath="/Users/xenomorph/Pictures/Lightroom/"
sourceVideosPath="/Users/xenomorph/Movies"
destinationSsdPicturePath="/Volumes/LightroomBak"

# echo "Do you want to back up NAS (y/N)"
# read includeNas 
# mount_smbfs $sourcePath/Developer /Volumes/TimeMachineExternal/xenomorph/Developer

# ec---------------------------------------"
SECONDS=0
# diskutil mount LightroomBak

echo "---------------------------------------------"
echo "Syncing from local to SSD"
echo "---------------------------------------------"
rsync -av --delete $sourcePicturesPath $destinationSsdPicturePath/Pictures/Lightroom
# cp -fanvR $sourcePicturesPath $destinationSsdPicturePath/Pictures

# echo "---------------------------------------------"
# echo "Picture copy completed"
# echo "---------------------------------------------"
# echo "Movie copy starting"
# echo "---------------------------------------------"

# rsync -av --delete $sourceVideosPath/CanonR5/ $destinationSsdPicturePath/Movies/CanonR5
# rsync -av --delete $sourceVideosPath/Davinci\ Resolve/ $destinationSsdPicturePath/Movies/Davinci\ Resolve
# rsync -av --delete $sourceVideosPath/EditVideos/ $destinationSsdPicturePath/Movies/EditVideos
# rsync -av --delete $sourceVideosPath/Lightroom/ $destinationSsdPicturePath/Movies/Lightroom
# cp -fanvR $sourceVideosPath/CanonR5/ $destinationSsdPicturePath/Movies/CanonR5
# cp -fanvR $sourceVideosPath/Davinci\ Resolve/ $destinationSsdPicturePath/Movies/Davinci\ Resolve
# cp -fanvR $sourceVideosPath/EditVideos/ $destinationSsdPicturePath/Movies/EditVideos
# cp -fanvR $sourceVideosPath/Lightroom/ $destinationSsdPicturePath/Movies/Lightroom

# echo "---------------------------------------------"
# echo "Movie copy completed"
# echo "---------------------------------------------"

# if [[ $includeNas == "Y" || $includeNas == "y" ]]
# then

# echo "---------------------------------------------"
# echo "Syncing movies on NAS"
# echo "---------------------------------------------"

# rsync -av $sourceVideosPath $nasDestinationPath/Movies

# echo "---------------------------------------------"
# echo "---------------------------------------------"
# echo "NAS movie copy completed"
# echo "---------------------------------------------"
# echo "---------------------------------------------"
# fi

# echo "---------------------------------------------"
# echo "Completed runtime: $(format_time $SECONDS)"
# echo "Source image count: \t\t$(ls -1R ~/Pictures|wc -l)"
# echo "Destination image count: \t$(ls -1R /Volumes/LightroomBak/Pictures|wc -l)"
# echo "Source video count: \t \t$(ls -1R ~/Movies|wc -l)"
# echo "Destination video count: \t$(ls -1R /Volumes/LightroomBak/Movies|wc -l)"
# echo "---------------------------------------------"

# diskutil eject LightroomBak