#!/bin/zsh
. Functions/format_time.sh

destinationPath="/Volumes/TimeMachineExternal/xenomorph"
dev="Developer"
desktop="Desktop"
download="Downloads"
document="Documents"
movie="Movies"
music="Music"
picture="Pirctures"
public="Public"
src="src"
library="Libarary"
ssh=".ssh"
#mount_smbfs $sourcePath/Developer /Volumes/TimeMachineExternal/xenomorph/Developer
echo Starting  folder
SECONDS=0
echo Starting $dev folder
rsync -rv ~/$dev/ $destinationPath/$dev/
echo Starting $download folder
rsync -rv ~/$download/ $destinationPath/$download/
echo Starting $desktop folder
rsync -rv ~/$desktop/ $destinationPath/$desktop/
echo Starting $document folder
rsync -rv ~/$document/ $destinationPath/$document/
echo Starting $movie folder
rsync -rv ~/$movie/ $destinationPath/$movie/
echo Starting $music folder
rsync -rv ~/$music/ $destinationPath/$music/
echo Starting $picture folder
rsync -rv ~/$picture/ $destinationPath/$picture/
echo Starting $public folder
rsync -rv ~/$public/ $destinationPath/$public/
echo Starting $src folder
rsync -rv ~/$src/ $destinationPath/$src/
echo Starting $library folder
rsync -rv ~/$library/ $destinationPath/$library/
echo Starting $ssh folder
rsync -rv ~/$ssh/ $destinationPath/$ssh/
# cp ~/.zsh* $destinationPath/

echo Completed runtime: $(format_time $SECONDS)
